# Generated by Django 5.1.3 on 2024-12-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devshortly", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="url",
            old_name="long_url",
            new_name="url",
        ),
        migrations.RemoveField(
            model_name="url",
            name="short_url",
        ),
        migrations.AddField(
            model_name="url",
            name="slug",
            field=models.SlugField(default="test"),
            preserve_default=False,
        ),
    ]
